## Stage 1: Base Image with Granite 2b Model Files
FROM docker.io/moosestack/ubi-modelcar-granite-3.3-2b-instruct:latest AS modelcar

##########################################################

## Stage 2: vLLM API Server
FROM public.ecr.aws/q9t5s3a7/vllm-cpu-release-repo:v0.9.0

# Copy the model files from the modelcar into the vLLM container
COPY --from=modelcar /models /models

# Copy the entrypoint script into the container
COPY --chmod=755 entrypoint.sh /entrypoint.sh

EXPOSE 8000

ENTRYPOINT [ "/entrypoint.sh" ]