FROM registry.access.redhat.com/ubi9/python-311:latest as base

## need root since creating /models
USER root

# Model repo name from Hugging Face are downloaded to /models
# https://huggingface.co/models
ENV HUGGINGFACE_MODEL_REPO=ibm-granite/granite-3.1-2b-instruct

RUN pip install huggingface-hub

COPY download_model.py .

RUN python download_model.py 

# Final image containing only the essential model files
FROM registry.access.redhat.com/ubi9/ubi-micro:9.4

# Copy the model files from the base container
COPY --from=base /models /models

USER 1001