name: Granite-3.3-2b Modelcar Container Build and Push

on:
  push:
    branches:
      - main
    paths:
      - modelcars/Containerfile_granite-3.3-2b-instruct

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./modelcars
          file: ./modelcars/Containerfile_granite-3.3-2b-instruct
          push: true
          tags: moosestack/ubi-modelcar-granite-3.3-2b-instruct:latest